version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vividmind_db
      POSTGRES_USER: vividmind_user
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-network

  web:
    build: .
    command: >
      sh -c "
        echo 'Waiting for Postgres...'; 
        until nc -z db 5432; do sleep 0.5; done; 
        echo 'Postgres is ready.'; 
        python manage.py makemigrations core; 
        python manage.py migrate; 
        python manage.py collectstatic --noinput; 
        gunicorn storagehouse.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:1.24
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
      - ./letsencrypt/webroot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro   # <-- mount host certificates
    depends_on:
      - web
    networks:
      - app-network
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge
