# Generated by Django 3.2 on 2025-02-13 12:08

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=36, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.CharField(max_length=255, unique=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
