# Generated by Django 3.2 on 2025-02-13 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
